#pragma once
// sharded_engine.hpp
//
// Multi-instrument, multi-threaded matching engine front-end.
//
// THE CONSTRAINT WE ARE NOT ALLOWED TO VIOLATE
// -----------------------------------------------
// docs/interview_questions.md and matching_engine.hpp are explicit
// that a single OrderBook/MatchingEngine is an inherently sequential
// data structure: two threads mutating the same book concurrently
// (even with "just a mutex around addOrder") would still need that
// mutex, so you gain nothing by having two threads *want* to touch
// the same book at the same time. Real HFT systems get parallelism by
// giving each INSTRUMENT its own single-writer engine, not by trying
// to make one book thread-safe internally.
//
// WHAT ShardedMatchingEngine ADDS (LEGACY COMPARISON PATH)
// --------------------------------------------------------
// This class is retained as a simple lock-based comparison architecture:
// instead of exactly one instrument (as in matching_engine_main) running
// on exactly one thread reading one SPSC queue, we now have:
//   - Several PRODUCER threads (e.g. several simulated feed sources)
//     generating orders for a MIX of symbols.
//   - Several CONSUMER/worker threads pulling from one shared
//     MPMCQueue<SymbolOrder> and applying whichever order they popped.
//   - Symbols are hashed into a fixed number of SHARDS
//     (kShardCount). Each shard owns its own mutex + a map of
//     Symbol -> MatchingEngine (one book per instrument, as always).
// A worker thread that pops an order for AAPL only ever contends with
// other workers that ALSO happen to be touching AAPL (i.e. hashed to
// the same shard) at that instant; workers processing MSFT and GOOG
// orders proceed fully in parallel on different cores. This preserves
// "one book, one writer at a time" while still giving genuine
// multi-core throughput across a multi-instrument workload.
//
// Important ordering caveat: when several workers pop from one shared
// MPMC queue, worker A can pop a same-symbol command first but worker B
// can acquire the shard mutex first. That preserves data-race safety but
// can reverse the intended same-symbol arrival order. The recommended
// PartitionedMatchingEngine avoids this by assigning one FIFO queue and
// one owner thread to each shard. This class remains useful for measuring
// the distinction between mutual exclusion and deterministic sequencing.
//
// Trades are appended to a shared, internally-locked TradeLog
// (std::deque-backed, see trade_log.hpp) so any thread can safely
// record/read recent executions regardless of which shard produced
// them.

#include <array>
#include <cstddef>
#include <mutex>
#include <unordered_map>
#include <vector>

#include "matching_engine.hpp"
#include "symbol.hpp"
#include "trade.hpp"
#include "trade_log.hpp"

namespace lob {

class ShardedMatchingEngine {
public:
    static constexpr size_t kShardCount = 8; // power of two: cheap `& (N-1)` routing

    explicit ShardedMatchingEngine(size_t trade_log_depth_per_symbol = 200)
        : trade_log_(trade_log_depth_per_symbol) {}

    // Thread-safe: may be called concurrently by any number of worker
    // threads, for any mix of symbols. Returns the number of trades
    // generated by this order (also appended to the shared TradeLog).
    size_t submit(const Symbol& symbol, Order order, std::vector<Trade>& out_trades) {
        const size_t before = out_trades.size();
        {
            Shard& shard = shardFor(symbol);
            std::lock_guard<std::mutex> lock(shard.mutex);
            MatchingEngine& engine =
                shard.engines[symbol]; // default-constructs on first sight
            engine.submitOrder(std::move(order), out_trades);
        }
        // Do not hold the book shard lock while taking the independent
        // global trade-log lock; this shortens the per-book critical path.
        for (size_t i = before; i < out_trades.size(); ++i) {
            trade_log_.record(symbol, out_trades[i]);
        }
        return out_trades.size() - before;
    }

    bool cancel(const Symbol& symbol, uint64_t order_id) {
        Shard& shard = shardFor(symbol);
        std::lock_guard<std::mutex> lock(shard.mutex);
        auto it = shard.engines.find(symbol);
        if (it == shard.engines.end()) return false;
        return it->second.cancelOrder(order_id);
    }

    // Snapshot of best bid/ask for `symbol`, or nullopt fields if the
    // book doesn't exist yet / is empty on that side.
    struct Snapshot {
        bool exists = false;
        std::optional<int64_t> best_bid;
        std::optional<int64_t> best_ask;
        size_t order_count = 0;
    };

    Snapshot snapshot(const Symbol& symbol) const {
        const Shard& shard = shardFor(symbol);
        std::lock_guard<std::mutex> lock(shard.mutex);
        auto it = shard.engines.find(symbol);
        if (it == shard.engines.end()) return {};
        Snapshot s;
        s.exists = true;
        s.best_bid = it->second.book().bestBid();
        s.best_ask = it->second.book().bestAsk();
        s.order_count = it->second.book().orderCount();
        return s;
    }

    const TradeLog& tradeLog() const { return trade_log_; }

private:
    struct Shard {
        mutable std::mutex mutex;
        std::unordered_map<Symbol, MatchingEngine> engines;
    };

    Shard& shardFor(const Symbol& symbol) {
        return shards_[std::hash<Symbol>{}(symbol) & (kShardCount - 1)];
    }
    const Shard& shardFor(const Symbol& symbol) const {
        return shards_[std::hash<Symbol>{}(symbol) & (kShardCount - 1)];
    }

    std::array<Shard, kShardCount> shards_;
    TradeLog trade_log_;
};

} // namespace lob
